### ISSUE TITLE
[FEAT]: Svelte 5 runes

### ISSUE THREAD

**Issue by emil14** [shinokada/svelte-ionicons#6]
### Description

Migrate to Svelte 5 runes mode so projects with enabled `runes: true` configuration can use this library

### Additional Information

```
[plugin:vite:import-analysis] Build failed with 1 error:
node_modules/svelte-ionicons/dist/HelpCircleOutline.svelte:19:9: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] /Users/emil/projects/editorx/web/node_modules/svelte-ionicons/dist/HelpCircleOutline.svelte:19:9 Cannot use $$props in runes mode
/Users/emil/projects/editorx/web/src/lib/components/navbar/NavbarSyncStatus.svelte
    at failureErrorWithLog (/Users/emil/projects/editorx/web/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/emil/projects/editorx/web/node_modules/esbuild/lib/main.js:1059:25
    at /Users/emil/projects/editorx/web/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
```

**Comment by shinokada** [comment]
You can use this library for Svelte-5.

**Comment by shinokada** [comment]
Now this lib can be used Svelte Runes.

```
pnpm i -D svelte-ionicons@next
```
